<Gerenciador>:
    Menu:
        name: 'menu'
    Compras:
        name: 'tarefas'
    Rennata:
        name: 'assistente'
	TelaAjuda:
	    name: 'telaajuda'

<Gerenciador2>:
    set_init:
    set_aten:
    set_desc:  
    
<Menu>:
    BoxLayout:
        orientation:'vertical'
        padding:root.width*0.10,root.height*0.1
        spacing:'10dp'
        canvas:
            Color:
                rgba:1,1,1,1
            Rectangle:
                size:self.size
                pos:self.pos
        Image:
            source:'logorenner1.png'
            size_hint_y:4
            allow_stretch:True
        Botao:
            text:'Compras'
            on_press:app.root.current = 'tarefas'
            cor: 1,0,0,1
            bold: True
            font_size: 50
        Botao:
            text:'Assistente'
            on_press:app.root.current = 'assistente'
            cor: 1,0,0,1
            bold: True
            font_size: 50
        Botao:
        	text:'Ajuda'
        	on_press:app.root.current = 'telaajuda'
        	cor: 1,0,0,1
        	bold: True
        	font_size: 50
        Botao:
            text:'Sair'
            on_press:app.stop()
            cor: 1,0,0,1
            bold: True
            font_size: 50
            
<TelaAjuda>:
    BoxLayout:
        orientation:'vertical'
        spacing: '10dp'
        canvas:
            Color:
                rgba:1,1,1,1
            Rectangle:
                size:self.size
                pos:self.pos
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Ajuda'
                    on_release:app.root.current = 'menu'
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
		ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:'40sp'
            TextInput:
                id:texto
            Button:
                text:'+'
                size_hint_x:None
                width:'40sp'
                on_release:root.addWidget()
        
<Compras>:
    BoxLayout:
        orientation:'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title:'Compras'
                    on_release:app.root.current = 'menu'
                ActionButton:
                    text:'Sair'
                    on_release:app.stop()
        ScrollView:
            BoxLayout:
                id:box
                orientation:'vertical'
                size_hint_y:None
                height:self.minimum_height
        BoxLayout:
            size_hint_y:None
            height:'40sp'
            TextInput:
                id:texto
            Button:
                text:'+'
                size_hint_x:None
                width:'40sp'
                on_release:root.addWidget()

<Tarefa>:
    size_hint_y:None
    height:'100sp'
    Label:
        id:label
        font_size:'20sp'
    Button:
        text:'X'
        size_hint_x:None
        width:'40sp'
        on_release:app.root.get_screen('tarefas').removeWidget(root)

<set_init>:
	name: 'inicial'
	BoxLayout:
		canvas:
	    	Color:
	    		rgba: 1, 1, 1, 1
	    	Rectangle:
	    		size: self.size
	    		pos: self.pos
		
		padding:root.width*0.05,root.height*0.05
		
		orientation: 'vertical'
			
		BoxLayout:
			padding:root.width*0.05,root.height*0.05
		
			Botao:
			    padding:root.width*0.05,root.height*0.05
	
	            text:'Desconto'
	
	            cor: 1,0,0,1
	            bold: True
	            font_size: 50
	            on_release: app.root.current: 'desconto'
	            
			Botao:
			    padding:root.width*0.05,root.height*0.05
			          
	            text:'Sair'
	            
	            cor: 1,0,0,1
	            bold: True
	            font_size: 50
	            on_release:app.root.current = 'menu'
				
		BoxLayout:
			padding:root.width*0.05,root.height*0.05
		
			Botao:
	            text:'Atendimento'
	            
				cor: 1,0,0,1
	            bold: True
	            font_size: 50
	            
	            on_release: app.root.current: 'atendimento'
	
<set_aten>:
	name: 'atendimento'
	BoxLayout:	
		canvas:
	    	Color:
	    		rgba: 1, 1, 1, 1
	    	Rectangle:
	    		size: self.size
	    		pos: self.pos
		
		padding:root.width*0.05,root.height*0.05
		
		orientation: 'vertical'
			
		BoxLayout:
			padding:root.width*0.05,root.height*0.05
		
			Botao:
			    padding:root.width*0.05,root.height*0.05
	
	            text:'Relatório'
	
	            cor: 1,0,0,1
	            bold: True
	            font_size: 50
	            
			Botao:
			    padding:root.width*0.05,root.height*0.05
			          
	            text:'Bug'
	            
	            cor: 1,0,0,1
	            bold: True
	            font_size: 50
				
		BoxLayout:
			padding:root.width*0.05,root.height*0.05
		
			Botao:
	            text:'Devolução'
	            
				cor: 1,0,0,1
	            bold: True
	            font_size: 50
	            
	        Botao:
	            text: 'Sair'
	            
	            cor: 1,0,0,1
	            bold: True
	            font_size: 50
            
<set_desc>:
	name: 'desconto'
	BoxLayout:
		canvas:
	    	Color:
	    		rgba: 1, 1, 1, 1
	    	Rectangle:
	    		size: self.size
	    		pos: self.pos
		
				
		padding:root.width*0.05,root.height*0.05
		
		orientation: 'vertical'
			
		BoxLayout:
			padding:root.width*0.05,root.height*0.05
		
			Botao:
			    padding:root.width*0.05,root.height*0.05
	
	            text:'Retornar'
	
				cor: 1,0,0,1
	            bold: True
	            font_size: 50

<Rennata>:
    		
    BoxLayout:
   
        orientation:'vertical'
		
		ScrollView:	
			BoxLayout:
				height: 10
				canvas:
					Color:
						rgba: 1, 1, 1, 1
						
					Rectangle:
						pos: self.pos
						size: self.size
	
		set_init:			
		Gerenciador2:
			Menu:
